inherit_from: configs/fusion/train_fusion.yaml
data:
  # path: /home/robin/Dev/MasterThesis/data/fusion/fusion_easy_data_temp
  # path_gt: /home/robin/Dev/MasterThesis/data/fusion/fusion_easy_data_gt_temp
  # path: /home/robin/Dev/MasterThesis/data/fusion
  # path_gt: /home/robin/Dev/MasterThesis/data/fusion_gt
  path: /home/robin/Dev/MasterThesis/data/fusion/single_box
  path_gt: /home/robin/Dev/MasterThesis/data/fusion/single_box_gt
  
training:
  out_dir: /home/robin/Dev/MasterThesis/data/output_fusion/single_voxel
  backbone_file: /home/robin/Dev/MasterThesis/data/output_backbone/models_backbone/aug_model_200000.pt
  learning_rate: 0.01
  limited_gpu: true
  checkpoint_every: 50
  log_comet: false 
  # print_every: 3