inherit_from: configs/fusion/train_fusion.yaml
data:
  path: /cluster/scratch/roberson/data/fusion/fusion_easy_data_temp
  path_gt: /cluster/scratch/roberson/data/fusion/fusion_easy_data_temp_gt
  # path: /cluster/scratch/roberson/data/fusion/fusion_wave
  # path_gt: /cluster/scratch/roberson/data/fusion/fusion_wave_gt

training:
  out_dir: /cluster/scratch/roberson/neuralblox/out_fusion/test_scene_easy_complete_logitsonly_diffdata
  backbone_file: /cluster/scratch/roberson/neuralblox/out_backbone/pointcloud/window_size_mixed_0.6_1.6_empty/aug_model_200000.pt
  checkpoint_every: 200
  limited_gpu: false
  save_data_viz: true
  log_comet: true
