inherit_from: configs/fusion/train_fusion.yaml
data:
  path: /cluster/scratch/roberson/data/fusion/fusion_2batches_robot_test
  path_gt: /cluster/scratch/roberson/data/fusion/fusion_2batches_gt_test
  # path: /cluster/scratch/roberson/data/fusion/fusion_wave
  # path_gt: /cluster/scratch/roberson/data/fusion/fusion_wave_gt
  # path: '/cluster/scratch/roberson/data/fusion/fusion_robot_temp'
  # path_gt: '/cluster/scratch/roberson/data/fusion/fusion_gt_temp'

training:
  out_dir: /cluster/scratch/roberson/neuralblox/out_fusion/test_full_scene_overfit
  starting_model_backbone_file: /cluster/scratch/roberson/neuralblox/out_backbone/pointcloud/trained_models/aug_model_20000.pt
  starting_model_merging_file: /cluster/scratch/roberson/neuralblox/out_fusion/temp_overfit/model_merging_0.pt
  model_backbone: model_backbone.pt
  model_merging: model_merging.pt
  checkpoint_every: 20
  limited_gpu: true
  save_data_viz: true
  log_comet: true
