inherit_from: configs/fusion/train_fusion.yaml
data:
  # points_subsample: 1000
  # path: /scratch2/roberson/data/fusion_easy_data_temp
  # path_gt: /scratch2/roberson/data/fusion_easy_data_gt_temp
  path: '/scratch2/roberson/data/fusion_easy_data_temp'
  path_gt: '/scratch2/roberson/data/fusion_easy_data_gt_temp'

  
  # path: /media/roberson/T7/data/fusion_debug/waves
  # path_gt: /media/roberson/T7/data/fusion_debug/waves_gt
  # path: /media/roberson/T7/data/fusion_debug/single_box
  # path_gt: /media/roberson/T7/data/fusion_debug/single_box_gt
training:
  # out_dir: /home/robin/Dev/MasterThesis/data/output_fusion/reduced_scenes
  out_dir: /scratch/roberson/neuralblox/out_fusion/test_gt_temp
  # backbone_file: /home/robin/Dev/MasterThesis/data/output_backbone/models_backbone/aug_model_130000.pt
  backbone_file: /scratch2/roberson/neuralblox/out_backbone/pointcloud/trained_models/aug_model_570000.pt
  learning_rate: 0.01
  limited_gpu: true
  checkpoint_every: 50
  log_comet: false 
  # print_every: 3
visualization: false
