inherit_from: configs/fusion/train_fusion.yaml
data:
  path: /media/roberson/T7/data/fusion_easy_data_temp
  path_gt: /media/roberson/T7/data/fusion_easy_data_gt_temp
  # path: /media/roberson/T7/data/fusion_wave
  # path_gt: /media/roberson/T7/data/fusion_wave_gt
training:
  out_dir: /scratch2/roberson/neuralblox/out_fusion/test_easy
  backbone_file: /scratch/roberson/neuralblox/out_backbone/pointcloud/window_size_mixed_0.6_1.6/aug_model_110000.pt
  learning_rate: 0.01
  limited_gpu: true
  checkpoint_every: 20
  log_comet: true 
  print_every: 3