method: neuralblox
data:
  dataset: Scenes3D
  input_type: pointcloud_sequential
  classes: null
  path: data/redwood_custom
  pointcloud_n: 30000
  pointcloud_noise: 0.000
  points_subsample: 8192
  points_file: points.npz
  points_iou_file: points.npz
  gt_file_name: 'pointcloud.npz'
  grid_resolution: 24
  points_unpackbits: true
  voxels_file: null
  unit_size: 0.02 # size of a voxel
  query_vol_size: 25
  return_category: true
  input_vol: 1.6
  query_vol: 1.0
model:
  local_coord: True
  encoder: pointnet_crop_local_pool_latent
  encoder_kwargs:
    hidden_dim: 32
    plane_type: ['grid']
    unet3d: True
    unet3d_kwargs:
      num_levels: 3 # define the receptive field, 3 -> 32, 4 -> 64
      f_maps: 32
      in_channels: 64
      out_channels: 64
    pos_encoding: sin_cos
  decoder: latent_to_logits
  decoder_kwargs:
    sample_mode: bilinear # bilinear / nearest
    hidden_size: 32
  pos_encoding: sin_cos
  c_dim: 32
training:
  out_dir: out/pointcloud_crop_training
  batch_size: 8
  model_selection_metric: iou
  model_selection_mode: maximize
  print_every: 100
  visualize_every: 1000
  validate_every: 10000
  checkpoint_every: 200
  backup_every: 2000
  n_workers: 8
  n_workers_val: 1
  stack_latents: true
  learning_rate: 0.01
  limited_gpu: false
  log_comet: true
test:
  threshold: 0.001
  eval_mesh: true
  eval_pointcloud: false
  model_file: model.pt
  
generation:
  generation_dir: generation
  vis_n_outputs: 2
  sliding_window: True
  resolution_0: 32
  upsampling_steps: 0