inherit_from: configs/simultaneous/train_simultaneous.yaml
data:
  classes: null
  path: /cluster/scratch/roberson/data/simultaneous/gt_robot
  grid_resolution: 24
  # pointcloud_noise: 0.005
  pointcloud_noise: 0.0
model:
  encoder_kwargs:
    grid_resolution: 24
training:
  out_dir: /cluster/scratch/roberson/neuralblox/out_simultaneous/simultaneous_training_gt_robot
  starting_model_backbone_file: /cluster/scratch/roberson/neuralblox/out_simultaneous/simultaneous_training_gt/model_backbone_25000.pt
  starting_model_merging_file: /cluster/scratch/roberson/neuralblox/out_simultaneous/simultaneous_training_gt/model_merging_25000.pt
  limited_gpu: true
  save_data_viz: true
  log_comet: true
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_backbone_file: model.pt
  model_merging_file: model_merging.pt
visualization: false