method: neuralblox
data:
  input_type: pointcloud
  classes: null
  path: null
  pointcloud_n: 4096 #number of inputs when loading for each frame
  pointcloud_noise: 0.005

  points_subsample: 40960 # number of points used for cost computation, total amount
  points_file: points.npz
  points_iou_file: points.npz
  points_unpackbits: true
  unit_size: 0.02 # size of a voxel
  query_vol_size: 25
  input_vol: 1.0
  query_vol: 1.0
model:
  local_coord: True
  encoder: pointnet_crop_local_pool_latent
  encoder_kwargs:
    grid_resolution: 24
    hidden_dim: 32
    plane_type: ['grid']
    unet3d: True
    unet3d_kwargs:
      num_levels: 3 # define the receptive field, 3 -> 32, 4 -> 64
      f_maps: 32
      in_channels: 64
      out_channels: 64
    pos_encoding: sin_cos
  decoder: simple_local_crop
  decoder_kwargs:
    sample_mode: bilinear # bilinear / nearest
    hidden_size: 32
  pos_encoding: sin_cos
  c_dim: 32
training:
  out_dir: null
  batch_size: 1
  model_selection_metric: iou
  model_selection_mode: maximize
  checkpoint_interval_minutes: 30
  print_every: 50
  backup_every: 100

  n_max_points: 2048 #max number of inputs per voxel (approx 400 occupied points per voxel)
  n_max_points_query: 8192 #max number of query points per voxel (between 900 to 3500 occupied points per voxel if no limitation)
  occ_per_query: 0.5

  n_workers: 8
  n_workers_val: 4
  reset_training: true
  monitor_gpu_usage: false 
  log_comet: false
  lr: 0.001
  lr_reduce_factor: 0.9
  lr_patience: 200
  starting_model_backbone_file: model_backbone.pt
  starting_model_merging_file: model_merging.pt
  model_backbone: model_backbone.pt
  model_merging: model_merging.pt
  limited_gpu: true
  save_data_viz: true
  n_voxels_max: 40
  return_flat: true # if true, cost computed on all voxels, if false, cost computed on some (not all) flat voxels + elevated voxels
  sigma: 0.8 # used for the weighting of the cost, lower sigma -> higher emphasis on points close to inputs
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_backbone_file: model.pt
  model_merging_file: model_merging.pt

generation:
  threshold: 0.02
  generation_dir: generation
  generation_dir_models: generation
  generator_type: neighbors
  model_backbone_file: model.pt
  model_merging_file: model_merging.pt
  refine: false
  n_x: 128
  n_z: 1
  vis_n_outputs: 2
  sliding_window: True
  resolution_0: 30
  voxel_threshold: 0.001

