inherit_from: configs/simultaneous/train_simultaneous.yaml
data:
  classes: null
  path: /cluster/scratch/roberson/data/simultaneous/sequential_training/gt_robot_straight_overfit
  pointcloud_noise: 0.005
  # pointcloud_noise: 0.0
training:
  out_dir: /cluster/scratch/roberson/neuralblox/out_simultaneous/sequential_training_robot_4h_02_July_overfit
  starting_model_backbone_file: /cluster/scratch/roberson/neuralblox/out_simultaneous/sequential_training_robot_4h_01_July_overfit/model_backbone_600.pt
  starting_model_merging_file: /cluster/scratch/roberson/neuralblox/out_simultaneous/sequential_training_robot_4h_01_July_overfit/model_merging_600.pt
  limited_gpu: true
  save_data_viz: true
  log_comet: true
  n_voxels_max: 25
test:
  model_backbone_file: model.pt
  model_merging_file: model_merging.pt
visualization: false