inherit_from: configs/simultaneous/train_simultaneous.yaml
data:
  classes:
  path: /scratch/roberson/data/simultaneous/sequential_training/gt_robot_straight_overfit
  pointcloud_noise: 0.005
generation:
  generation_dir_models: /scratch/roberson/neuralblox/out_simultaneous/models
  generation_dir: /scratch/roberson/neuralblox/simultaneous/meshes
  generator_type: neighbors
  model_backbone_file: model_backbone_600.pt
  model_merging_file: model_merging_600.pt
  resolution_0: 50
  threshold: 0.02
test:
  model_backbone_file: model.pt
  model_merging_file: model_merging.pt
training:
  limited_gpu: true
  log_comet: false
  out_dir: /scratch/roberson/neuralblox/out_simultaneous/sequential_training_robot
  save_data_viz: true
  starting_model_backbone_file: /scratch/roberson/neuralblox/out_simultaneous/models/model_backbone_600.pt
  starting_model_merging_file: /scratch/roberson/neuralblox/out_simultaneous/models/model_merging_600.pt
  n_voxels_max: 20
visualization: false
