inherit_from: configs/simultaneous/train_simultaneous.yaml
data:
  classes: null
  path: /cluster/scratch/roberson/data/simultaneous/gt_only
  grid_resolution: 24
  # pointcloud_noise: 0.005
  pointcloud_noise: 0.0
  points_subsample: 16384
  points_iou_subsample: 16384
model:
  encoder_kwargs:
    grid_resolution: 24
training:
  out_dir: /cluster/scratch/roberson/neuralblox/out_simultaneous/simultaneous_training_gt
  starting_model_backbone_file: /cluster/scratch/roberson/neuralblox/out_backbone/pointcloud/window_size_mixed_0.6_1.6_empty_new_reso24_may23/aug_model_20000.pt
  starting_model_merging_file: /cluster/scratch/roberson/neuralblox/out_fusion/temp_overfit/model_merging_0.pt
  model_backbone: model_backbone.pt
  model_merging: model_merging.pt
  limited_gpu: false
  save_data_viz: true
  log_comet: true
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_backbone_file: model.pt
  model_merging_file: model_merging.pt
visualization: false


