inherit_from: configs/simultaneous/train_simultaneous.yaml
data:
  classes: null
  path: /cluster/scratch/roberson/data/backbone/window_size_mixed_0.6_1.6_empty_full
  grid_resolution: 24
model:
  encoder_kwargs:
    grid_resolution: 24
training:
  out_dir: /cluster/scratch/roberson/neuralblox/out_backbone/pointcloud/window_size_mixed_0.6_1.6_empty_new_reso24_june
  starting_model_backbone_file: /scratch2/roberson/neuralblox/out_backbone/pointcloud/trained_models/aug_model_20000.pt
  starting_model_merging_file: /scratch/roberson/neuralblox/out_fusion/temp_overfit/model_merging_0.pt
  model_backbone: model_backbone.pt
  model_merging: model_merging.pt
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_backbone_file: model.pt
  model_merging_file: model_merging.pt

