inherit_from: configs/simultaneous/train_simultaneous.yaml
data:      
  path: /media/roberson/T7/data/sequential/sequential_training/set_s45_b3_l20       
  val_classes: ['2024-08-21_16-54-17']
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                #took the last 2 out '2024-06-27_15-12-02', '2024-06-27_15-12-03' 
  transform:
    specific_angle: true
    angle_x: 0
    angle_y: 33
    angle_z: 0
    specific_translation: false
    # translation_x: 0.5
    # translation_y: 0.5
    # translation_z: 0.5
    translation_x: 0.
    translation_y: 0.
    translation_z: 0.
    # angle_x: 0
    # angle_y: 33
    # angle_z: 0
generation:
  generation_dir_models: /scratch/roberson/neuralblox/out_simultaneous/models
  generation_dir: /scratch/roberson/neuralblox/simultaneous/meshes
  generator_type: neighbors
  model_backbone_file: model_backbone.pt
  model_merging_file: model_merging.pt
  resolution_0: 50
  prob_threshold: 0.1
  n_max_inputs: 2000

test:
  model_backbone_file: model.pt
  model_merging_file: model_merging.pt
training:
  checkpoint_interval_minutes: 0
  limited_gpu: true
  log_comet: false
  out_dir: /scratch/roberson/neuralblox/out_simultaneous/sequential_training_robot-overfit
  save_data_viz: true
  starting_model_backbone_file: /media/roberson/T7/neuralblox/sequential/models/model_backbone.pt
  starting_model_merging_file: /media/roberson/T7/neuralblox/sequential/models/model_merging.pt

  # starting_model_backbone_file: /scratch/roberson/neuralblox/out_simultaneous/sequential_training_robot/model_backbone.pt
  # starting_model_merging_file: /scratch/roberson/neuralblox/out_simultaneous/sequential_training_robot/model_merging.pt
  n_seq_scene: 3
  n_voxels_max: 100
  n_batch: 50
  batch_group_size: 7

visualization: true
k_value: 0.2
