inherit_from: configs/simultaneous/train_simultaneous.yaml
data:
  # classes: ['2024-06-27_15-00-39', '2024-06-27_15-01-39', '2024-06-27_15-01-40', '2024-06-27_15-01-42', '2024-06-27_15-01-46', '2024-06-27_15-01-48', '2024-06-27_15-01-51', '2024-06-27_15-01-55', '2024-06-27_15-01-57', '2024-06-27_15-01-58', '2024-06-27_15-01-59', '2024-06-27_15-02-00', '2024-06-27_15-02-01', '2024-06-27_15-02-02', '2024-06-27_15-02-03', '2024-06-27_15-11-13', '2024-06-27_15-11-14', '2024-06-27_15-11-15', '2024-06-27_15-11-18', '2024-06-27_15-11-19', '2024-06-27_15-11-23', '2024-06-27_15-11-31', '2024-06-27_15-11-34', '2024-06-27_15-11-35', '2024-06-27_15-11-37', '2024-06-27_15-11-38', '2024-06-27_15-11-41', '2024-06-27_15-11-45', '2024-06-27_15-11-46', '2024-06-27_15-11-48', '2024-06-27_15-11-53'] #took the last 2 out '2024-06-27_15-12-02', '2024-06-27_15-12-03' 
  train_classes: null
  val_classes: null
  path: /cluster/scratch/roberson/data/simultaneous/sequential_training/gt_robot_s20_b3_l20
  pointcloud_noise: 0.000
  transform:
    specific_angle: false
    angle_x: 5
    angle_y: 180
    angle_z: 0
training:
  out_dir: /cluster/scratch/roberson/neuralblox/out_simultaneous/sequential_120h_19_August_transT_x5_y180_gt_robot_s20_b3_l20-lr0_002-Scratch
  starting_model_backbone_file: /cluster/scratch/roberson/neuralblox/out_simultaneous/sequential_120h_19_August_transT_x5_y180_gt_robot_s20_b3_l20-lr0_002-Scratch/model_backbone.pt
  starting_model_merging_file: /cluster/scratch/roberson/neuralblox/out_simultaneous/sequential_120h_19_August_transT_x5_y180_gt_robot_s20_b3_l20-lr0_002-Scratch/model_merging.pt
  # starting_model_merging_file: /cluster/scratch/roberson/neuralblox/out_simultaneous/sequential_training_robot_24h_23_July_gt_robot_x5_y180_s10_b20/model_merging.pt
  # out_dir: /cluster/scratch/roberson/neuralblox/out_simultaneous/sequential_training_robot_4h_17_July_gt_robot_-10to10_5scenes_lr0001
  limited_gpu: true
  save_data_viz: true
  log_comet: true
  n_voxels_max: 30
  n_batch: 50
  lr: 0.002
  load_optimizer: true
  n_seq_scene: 3
  batch_group_size: 7
generation:
  generation_dir_models: /cluster/scratch/roberson/neuralblox/out_simultaneous/models
  generation_dir: /cluster/scratch/roberson/neuralblox/out_simultaneous/meshes
  model_backbone_file: model_backbone.pt
  model_merging_file: model_merging.pt
  resolution_0: 75
  prob_threshold: 0.1

visualization: false