method: neuralblox
data:
  input_type: pointcloud
  classes: ['2024-03-27_11-27-45', '2024-03-27_11-27-52', '2024-03-27_11-27-57', '2024-03-27_11-28-03', '2024-03-27_11-28-34', '2024-03-27_11-28-35', '2024-03-27_11-30-06', '2024-03-27_11-30-07', '2024-03-27_11-30-08', '2024-03-27_11-30-09', '2024-03-27_11-30-10', '2024-03-27_11-30-11', '2024-03-27_11-30-12', '2024-03-27_11-30-13', '2024-03-27_11-30-14']
  # classes: null
  # classes: ['04530566']
  path: /media/roberson/T7/data/backbone_data/window_size_1_6
  pointcloud_n: 3000
  pointcloud_noise: 0.005
  points_subsample: 2048
  points_file: points.npz
  points_iou_file: points.npz
  # points_unpackbits: false
  voxels_file: null
  unit_size: 0.02 # size of a voxel
  query_vol_size: 25
  grid_resolution: 24
  input_vol: 1.6
  query_vol: 1.0
model:
  encoder: pointnet_local_pool
  encoder_kwargs:
    hidden_dim: 32
    plane_type: 'grid'
    grid_resolution: 24
    pos_encoding: True
    unet3d: True
    unet3d_kwargs:
      num_levels: 3
      f_maps: 32
      in_channels: 32
      out_channels: 32
  decoder: simple_local      
  decoder_kwargs:
    sample_mode: bilinear # bilinear / nearest
    hidden_size: 32
  c_dim: 32
training:
  out_dir: /scratch/roberson/neuralblox/out_backbone/pointcloud/window_size_1_6
  batch_size: 64
  model_selection_metric: iou
  model_selection_mode: maximize
  print_every: 1000
  visualize_every: 10000
  validate_every: 10000
  checkpoint_every: 2000
  backup_every: 10000
  n_workers: 8
  n_workers_val: 4
  reset_training: false
  starting_model: model.pt
  # starting_model: model.pt
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_file: model.pt
generation:
  vis_n_outputs: 2
  refine: false
  n_x: 128
  n_z: 1
  max_byte_size: 600000000