inherit_from: configs/fusion/train_backbone.yaml
data:
  classes: null
  path: /cluster/scratch/roberson/data/backbone/window_size_mixed_0.6_1.6_empty_full
training:
  out_dir: /cluster/scratch/roberson/neuralblox/out_backbone/pointcloud/window_size_mixed_0.6_1.6_empty
  batch_size: 256
  print_every: 1000
  visualize_every: 5000
  validate_loss_every: 5000
  checkpoint_every: 2000
  starting_model: model.pt
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_file: model.pt