inherit_from: configs/pointcloud/train_backbone.yaml
data:
  classes: null
  path: /scratch/roberson/data/backbone/window_size_mixed_0.6_1.6_empty_full_test
training:
  out_dir: /scratch2/roberson/neuralblox/out_backbone/pointcloud/window_size_mixed_0.6_1.6
  batch_size: 64
  print_every: 100
  visualize_every: 100
  validate_loss_every: 500000
  checkpoint_every: 2000
  starting_model: model.pt
  log_comet: false
  lr: 0.01

test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_file: aug_model_40000.pt

