inherit_from: configs/pointcloud/train_backbone.yaml
data:
  classes: null
  path: /scratch/roberson/data/backbone/window_size_mixed_0.6_1.6_empty_only_test
training: 
  out_dir: /scratch2/roberson/neuralblox/out_backbone/pointcloud/trained_models
  batch_size: 64
  print_every: 100
  visualize_every: 100
  validate_loss_every: 5000
  checkpoint_every: 500
  starting_model: aug_model_100000.pt
  log_comet: false
  lr: 0.01
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_file: aug_model_100000.pt

