method: neuralblox
data:
  input_type: pointcloud
  # classes: ['2024-03-27_11-27-45', '2024-03-27_11-27-52', '2024-03-27_11-27-57', '2024-03-27_11-28-03', '2024-03-27_11-28-34', '2024-03-27_11-28-35', '2024-03-27_11-30-06', '2024-03-27_11-30-07', '2024-03-27_11-30-08', '2024-03-27_11-30-09', '2024-03-27_11-30-10', '2024-03-27_11-30-11', '2024-03-27_11-30-12', '2024-03-27_11-30-13', '2024-03-27_11-30-14']
  classes: null
  # classes: ['04530566']
  path: null
  pointcloud_n: 3000
  pointcloud_noise: 0.005
  points_subsample: 2048
  points_iou_subsample: 6000
  points_file: points.npz
  points_iou_file: points.npz
  # points_unpackbits: false
  voxels_file: null
  unit_size: 0.02 # size of a voxel
  query_vol_size: 25
  grid_resolution: 24
  input_vol: 1.2
  query_vol: 1.0
  vol_range: [[-0.55, -0.55, -0.55], [0.55, 0.55, 0.55]]
  # vol_range: [[0.0, 0.0, 0.0], [1.0, 1.0, 1.0]]
model:
  local_coord: True
  encoder: pointnet_crop_local_pool_latent
  encoder_kwargs:
    grid_resolution: 24
    hidden_dim: 32
    plane_type: ['grid']
    unet3d: True
    unet3d_kwargs:
      num_levels: 3 # define the receptive field, 3 -> 32, 4 -> 64
      f_maps: 32
      in_channels: 64
      out_channels: 64
    pos_encoding: sin_cos
  decoder: simple_local_crop
  decoder_kwargs:
    sample_mode: bilinear # bilinear / nearest
    hidden_size: 32
  pos_encoding: sin_cos
  c_dim: 32
training:
  out_dir: null
  batch_size: 256
  model_selection_metric: iou
  model_selection_mode: maximize
  print_every: 1000
  visualize_every: 10000
  validate_loss_every: 5000
  checkpoint_every: 2000
  backup_every: 10000
  n_workers: 8
  n_workers_val: 4
  reset_training: true
  starting_model: model.pt
  monitor_gpu_usage: false 
  # starting_model: model.pt
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
  model_file: model.pt

generation:
  vis_n_outputs: 2
  refine: false
  n_x: 128
  n_z: 1
  resolution_0: 20