inherit_from: configs/simultaneous/train_simultaneous.yaml
data:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             #took the last 2 out '2024-06-27_15-12-02', '2024-06-27_15-12-03' 
  path: /media/roberson/T7/data/sequential/sequential_training/training_s25_b3_l20
  scene_folder: /media/roberson/T7/terrains
  pointcloud_noise: 0.0
  pointcloud_n: 8192 #number of inputs when loading for each frame

  transform:
    specific_angle: true
    angle_x: 0
    angle_y: 33
    angle_z: 0
    specific_translation: true
    translation_x: 0
    translation_y: 0.1
    translation_z: 0

generation:
  generation_dir: /media/roberson/T7/neuralblox/sequential
  points_threshold: 10
  dataset: train

  model_backbone_file: model_backbone.pt
  model_merging_file: model_merging.pt

  prob_threshold: 0.1
  resolution_0: 60
  skip_frames: 1
  n_max_inputs: 8192
  idx_vis: 10
  folder_gen: 18_08_q1i1

test:
  model_backbone_file: model.pt
  model_merging_file: model_merging.pt

training:
  limited_gpu: true
  log_comet: false
  save_data_viz: true
  starting_model_backbone_file: /media/roberson/T7/neuralblox/sequential/models/model_backbone.pt
  starting_model_merging_file: /media/roberson/T7/neuralblox/sequential/models/model_merging.pt
  n_seq_scene: 3
  n_voxels_max: 1000
  batch_group_size: 1

evaluation:
  skip_frames: 1
  n_max_inputs: 8192
  n_logits: 20000
  prob_threshold: 0.01
  n_max_query_points: 50000
  discard_ground: true
  tau_r: 0.05
  visualize: true
